/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */



#include <stdint.h>

#include "structs.h"
#include <string.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

// EXTI INTERRUPT İLE IR SENSOR KULLANIM KODU
// KOD DİREKT OLARAK İNTERRUPT DİREVEN OLARAK YAZILDI - PA3 PIN - - IR SENSOR

#define EXTI_BASE_ADDR 0x4002F400


#define SWITCH_PIN 6
#define LED_PIN 5


#define EXTI_IMR1 (*((volatile uint32_t *)(EXTI_BASE_ADDR + 0x80)))
#define EXTI_RTSR1 (*((volatile uint32_t *)(EXTI_BASE_ADDR + 0x00)))
#define EXTI_FTSR1 (*((volatile uint32_t *)(EXTI_BASE_ADDR + 0x04)))
#define EXTI_RPR1 (*((volatile uint32_t *)(EXTI_BASE_ADDR + 0xC)))
#define EXTI_FPR1 (*((volatile uint32_t *)(EXTI_BASE_ADDR + 0x10)))



void init_interrupts() {
    GPIOA->MODER &= ~(3 << (SWITCH_PIN * 2)); // Set mode register to input

    // Configure EXTI for switch pin

    EXTI_IMR1 |= 1 << SWITCH_PIN; // Enable EXTI6 interrupt
    EXTI_RTSR1 |= 1 << SWITCH_PIN; // Enable rising edge trigger
    EXTI_FTSR1 |= 1 << SWITCH_PIN; // Enable falling edge trigger
    ISER0 |= 1 << 17; // Enable EXTI6 in NVIC(position 17)
}

void init_userleds (void){
	RCC_AHB2ENR |= (1<<0) ;
	RCC_AHB2ENR |= (1<<1) ;
	RCC_AHB2ENR |= (1<<2) ;


	GPIOC->MODER &= ~ (1<< 15);  // PC7 output mode açılır
	GPIOA->MODER &= ~ (1<< 19);   // PA9 output mode açılır
	GPIOB->MODER &= ~ (1<< 15);   // PB7 output mode açılır

	GPIOA->MODER &= ~ (3<< 6); // pa3 clear bits
	GPIOA->MODER  |= (1<<6) ;  // pa3 output mode

	GPIOC->MODER &= ~(3 << 2*1);   //  // PC1 input for IR sensor

}



void EXTI6_IRQHandler(void) {

    if ((EXTI_RPR1 & (1U << SWITCH_PIN)) != 0) { // Check if EXTI interrupt occurred
        EXTI_RPR1 = 1U << SWITCH_PIN; // Clear EXTI interrupt flag
        GPIOA->ODR   &= ~ (1<<3) ;  //pa3 close
    }

    if ((EXTI_FPR1 & (1U << SWITCH_PIN)) != 0) { // Check if EXTI interrupt occurred
        EXTI_FPR1 = 1U << SWITCH_PIN; // Clear EXTI interrupt flag

        GPIOA->ODR  |= (1<<3) ; // pa3 open
    }

}





void turn_on_red(void ){

	GPIOA->ODR  |= (1<<9) ;  // pa9 açılır _red led yanar
}

void turn_off_red(void ){

	GPIOA->ODR   &= ~ (1<<9) ;  // pa9 kapanır _red led söner
}

uint32_t check_IR_Sensor (void){
    // Debug amaçlı GPIOC IDR değerini gözlemlemek
	return (GPIOC->IDR & (1 << 1)) >> 1; // Read PC1 pin status
}

int main(void)
{


	 init_userleds();
	 init_interrupts();

	    __asm volatile(
	        "mov r0, #0 \n\t"
	        "msr primask, r0 \n\t"
	    ); // Enable interrupts

	 while (1) {
	         // Main loop can be empty, LED is controlled by interrupt

		  __asm volatile("wfi"); // Wait for interrupt
	}



}


