/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

// soru : pb10 ve pb11 pinlerini kullanarak led yakalım
// pb10 -> 1  , pb11 -> 0 olsun



#include <stdint.h>

#define RCC_AHB2ENR *( (volatile uint32_t *) 0x4002104C)
#define GPIOB_MODER *( (volatile uint32_t *) 0x42020400 )
#define GPIOB_ODR   *( (volatile uint32_t *)   0x42020414 )




void init_led1 (void){
	RCC_AHB2ENR |= (1<<1) ;
	GPIOB_MODER &= ~ (1<< 21);

}

void turn_on_led1(void ){
	GPIOB_ODR  |= (1<<10) ;
}

void turn_off_led1(void ){
	GPIOB_ODR  &= ~ (1<< 10);
}


int main(void)
{
init_led1();
   while(1){
	   turn_on_led1();
	   for (volatile int i = 0; i < 200000; i++) {} // Adjust the loop count for your desired delay

	   turn_off_led1();
	   for (volatile int i = 0; i < 200000; i++) {} // Adjust the loop count for your desired delay


   }
}

