/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

// Question : Board üzerindeki ledleri sırayla yakıp söndür

// A green user LED is connected to the PC7
//A blue user LED is connected to PB7.
// A red user LED is connected to PA9


#include <stdint.h>

#define RCC_AHB2ENR *( (volatile uint32_t *) 0x4002104C)

#define GPIOA_MODER *( (volatile uint32_t *)  0x42020000 )
#define GPIOB_MODER *( (volatile uint32_t *) 0x42020400 )

#define GPIOC_MODER *( (volatile uint32_t *) 0x42020800 )


#define GPIOA_ODR  *( (volatile uint32_t *)   0x42020014  )
#define GPIOB_ODR   *( (volatile uint32_t *)   0x42020414 )
#define GPIOC_ODR   * ( (volatile uint32_t *)    0x42020814)





void init_userleds (void){
	RCC_AHB2ENR |= (1<<0) ;
	RCC_AHB2ENR |= (1<<1) ;
	RCC_AHB2ENR |= (1<<2) ;


	GPIOC_MODER &= ~ (1<< 15);  // PC7 output mode açılır
	GPIOA_MODER &= ~ (1<< 19);   // PA9 output mode açılır
	GPIOB_MODER &= ~ (1<< 15);   // PB7 output mode açılır

}

void turn_on_green(void ){
	GPIOC_ODR  |= (1<<7) ;  // PC7 açılır _green led yanar
}

void turn_on_red(void ){

	GPIOA_ODR  |= (1<<9) ;  // pa9 açılır _red led yanar
}

void turn_on_blue(void ){

	GPIOB_ODR  |= (1<<7) ;  // pb7 açılır _blue led yanar
}


void turn_off_green(void ){
	GPIOC_ODR  &= ~ (1<<7) ;  // PC7 kapanır _green led söner
}

void turn_off_red(void ){

	GPIOA_ODR   &= ~ (1<<9) ;  // pa9 kapanır _red led söner
}

void turn_off_blue(void ){

	GPIOB_ODR   &= ~ (1<<7) ;  // pb7 kapanır _blue led söner
}




int main(void)
{
init_userleds();

   while(1){
	   turn_on_green();
	   for (volatile int i = 0; i < 200000; i++) {} // Adjust the loop count for your desired delay

	   turn_on_red();
	   for (volatile int i = 0; i < 200000; i++) {} // Adjust the loop count for your desired delay

	   turn_on_blue();
	   for (volatile int i = 0; i < 200000; i++) {} // Adjust the loop count for your desired delay

	   turn_off_green();
	   turn_off_red();
	   turn_off_blue();

	   for (volatile int i = 0; i < 200000; i++) {} // Adjust the loop count for your desired delay

   }
}

