/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

// Seven segment display code
// pb0 - pb7 arası pinler kullanıldı
// common anot ve common kathode için kod yazıldı
// Hemde generic kod yazıldı,



#include <stdbool.h>
#include <stdint.h>

#define RCC_AHB2ENR *( (volatile uint32_t *) 0x4002104C)

#define GPIOB_MODER *( (volatile uint32_t *) 0x42020400 )

#define GPIOB_ODR   *( (volatile uint32_t *)   0x42020414 )





void init_sevensegment (void){

	RCC_AHB2ENR |= (1<<1) ;   // port B clock open

	GPIOB_MODER &= ~(0xFFFF);   // clear bits 0-15

	GPIOB_MODER  |= (0b0101010101010101) ;  // Set bits to '01' for pins 0-7  ( 01010101)

}


//Code for common cathode
//cmpe443 dersinde common cathod kullanılıyor
// pb0 -> a , PB1 -> b, pb2 -> c vs,  ortadakilerde(com olanlar) ortak olarak gnd'ye gidiyor, gnd öncesi direnç bağlanır
void write_to_sevensegment_cathode (uint8_t number){

	static const uint8_t seven_segment_cathode[10]={0x3FU,0x06U,0x5BU,0x4FU,0x66U,0x6DU,0x7DU,0x07U,0x7FU,0x6FU};

	GPIOB_ODR &= ~(0xFFU) ; // Clear the pin interface of 7S
	GPIOB_ODR |= seven_segment_cathode[number]; //write val to the 7S

}



void wait(){
	for (volatile int i = 0; i < 500000; i++) {}
}


// General code for both common anode and common cathode
void write_to_sevensegment(uint8_t number, bool is_anode) {
    static const uint8_t seven_segment_values[10] = {
        0x3FU, 0x06U, 0x5BU, 0x4FU, 0x66U, 0x6DU, 0x7DU, 0x07U, 0x7FU, 0x6FU
    };

    uint8_t value_to_write;

    if (is_anode) {
        // Anode display için bitleri ters çeviriyoruz
        value_to_write = ~seven_segment_values[number];
    } else {
        // Cathode display için doğrudan yazıyoruz
        value_to_write = seven_segment_values[number];
    }

    GPIOB_ODR &= ~(0xFFU);         // 7 segment display’in pinlerini temizler
    GPIOB_ODR |= value_to_write;   // 7 segment display’e değeri yazar
}



void write_to_sevensegment_shift (uint8_t number, bool is_anode, uint8_t shift) {
    // Segment değerleri
    static const uint8_t seven_segment_cathode[10] = {0x3FU, 0x06U, 0x5BU, 0x4FU, 0x66U, 0x6DU, 0x7DU, 0x07U, 0x7FU, 0x6FU};
    static const uint8_t seven_segment_anode[10]   = {~0x3FU, ~0x06U, ~0x5BU, ~0x4FU, ~0x66U, ~0x6DU, ~0x7DU, ~0x07U, ~0x7FU, ~0x6FU};

    // Önce tüm pinleri temizle
    GPIOB->ODR &= ~(0xFFU << shift);

    // Anode veya cathode segment seçimi yaparak kaydırılmış değeri yaz
    if (is_anode) {
        GPIOB->ODR |= (seven_segment_anode[number] << shift);
    } else {
        GPIOB->ODR |= (seven_segment_cathode[number] << shift);
    }
}



int main(void)
{
	init_sevensegment ();
	int number=0;

   while(1){

	   write_to_sevensegment_cathode(number);
	   //write_to_sevensegment(number, false);
	   wait();
	   number++;
	   if(number>= 10){
		   number=0;
	   }


   }
}

