/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

// Question: Switch on/off yapılarak, board üzerindeki  renklerin yanıp sönmesi

// A green user LED is connected to the PC7
//A blue user LED is connected to PB7.
// A red user LED is connected to PA9
// PC13 te input idr olacak , SWİTCH ortası bağlı


#include <stdint.h>

#define RCC_AHB2ENR *( (volatile uint32_t *) 0x4002104C)

#define GPIOA_MODER *( (volatile uint32_t *)  0x42020000 )
#define GPIOB_MODER *( (volatile uint32_t *) 0x42020400 )

#define GPIOC_MODER *( (volatile uint32_t *) 0x42020800 )


#define GPIOA_ODR  *( (volatile uint32_t *)   0x42020014  )
#define GPIOB_ODR   *( (volatile uint32_t *)   0x42020414 )
#define GPIOC_ODR   * ( (volatile uint32_t *)    0x42020814)

#define GPIOC_IDR *( (volatile uint32_t *) 0x42020810 )

#define SW_OPEN 1<<13
#define SW_CLOSED 0





void init_userleds (void){
	RCC_AHB2ENR |= (1<<0) ;
	RCC_AHB2ENR |= (1<<1) ;
	RCC_AHB2ENR |= (1<<2) ;


	GPIOC_MODER &= ~ (1<< 15);  // PC7 output mode açılır
	GPIOA_MODER &= ~ (1<< 19);   // PA9 output mode açılır
	GPIOB_MODER &= ~ (1<< 15);   // PB7 output mode açılır

	GPIOC_MODER &= ~ (3<< 26);   // PC13 input mode açılır

}

void turn_on_green(void ){
	GPIOC_ODR  |= (1<<7) ;  // PC7 açılır _green led yanar
}

void turn_on_red(void ){

	GPIOA_ODR  |= (1<<9) ;  // pa9 açılır _red led yanar
}

void turn_on_blue(void ){

	GPIOB_ODR  |= (1<<7) ;  // pb7 açılır _blue led yanar
}


void turn_off_green(void ){
	GPIOC_ODR  &= ~ (1<<7) ;  // PC7 kapanır _green led söner
}

void turn_off_red(void ){

	GPIOA_ODR   &= ~ (1<<9) ;  // pa9 kapanır _red led söner
}

void turn_off_blue(void ){

	GPIOB_ODR   &= ~ (1<<7) ;  // pb7 kapanır _blue led söner
}

uint32_t check_User_pb(void){
	//returns 0 if SW1 is closed
	 //returns 1<<13 if SW1 is open
	return (GPIOC_IDR & (1<<13) );

}


int main(void)
{
	init_userleds();

   while(1){
	   while (check_User_pb() == SW_OPEN);
		   turn_on_green();
		   turn_off_red();

	   while(check_User_pb() == SW_CLOSED );
		   turn_off_green();
		   turn_on_red();


   }
}

