/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

// USB-TTL DONUSTURUCU KULLANARAK UART IMPLEMENTASYONU
// PD8 PİN - TTL de RX pinine bağlanır
// PD9 PİN -- TTL de TX pinine bağlanır  yani çapraz bağlanılır

#include <stdint.h>

#include "structs.h"
#include <string.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void initGPIO(){

	//PD8 ve pd9 usart3 için enable edilir
	RCC_AHB2ENR |= 1<<3;  // GPIOD enable edilir
	GPIOD->MODER &= ~(3 << 2*8);  // PD8 alternatif fonksiyon moduna alınır
	GPIOD->MODER |= (2 << 2*8);  // 16. biti 10 yapılır alternate mode

	GPIOD->MODER &= ~(3 << 2*9);  // PD9 alternatif fonksiyon moduna alınır
	GPIOD->MODER |= (2 << 2*9);  // 18. biti 10 yapılır alternate mode


	GPIOD->AFRH  |=  7<<0*4 ;   // PD8 pini AF7 olarak ayarlandı  USART-TX
	GPIOD->AFRH  |=  7 << 1*4 ;   // PD9 pini AF7 olarak ayarlandı  - USART-RX



}


//  63 71 Settable USART3 USART3 global interrupt
// ıser1 - 31.adres


void init_USART3(){

	RCC_APB1ENR1  |= (1<<18) ;  // 18.bit usart3 enable eder // enable clock source


	RCC_CCIPR1 = 1 <<4 ; //sys clock active , 4mhz msi


	USART3->CR1 &= ~(1 << 28);  // M1: Word length   00 -> 8  data bits
	USART3->CR1 &= ~(1 << 12);  // M0: Word length

	USART3->CR2 &= ~(3 << 12);  // program the number of stop bits in LPUART_CR2. stop bit:1

	USART3->CR1 |= (1 << 3);  // Bit 3 TE: Transmitter enable (iletme)
	USART3->CR1 |= (1 << 2); // Bit 2 RE: Receiver enable (alma)

	// 9600 braud rate, SYSCLOCK, MSI 4 mhz clock , Oversampling 16 ,  hex : 1A0
	USART3->BRR |= 0x1A0 ;

	// 115200 braud rate, SYSCLOCK, MSI 4 mhz clock , Oversampling 16 ,  hex : 22
	// USART3->BRR |= 0x0022 ;


	//USART3->CR1 |= (1 << 5); //RX interrupt enable
	// USART3->CR |= (1 << 7); //TX interrupt enable


	//Enable Interrupt and USART3
	//63 71 Settable USART3 USART3 global interrupt  position 63
	//NVIC->ISER[1] = 1 << 31;		//  position : 63 = 32 + 31

	//Enable USART3
	USART3->CR1 |= 1 ; // usart3 enable
}


// data transmission txt
void USART3_SendChar(char c) {

	USART3->TDR = c;                  // Transmit data
    while (!(USART3->ISR & (1 << 6))); // Wait until TXE is set

}


// data read rx
char USART3_ReceiveChar(void) {
	char temp;

    while (!(USART3->ISR & (1 << 5))); // Wait until RXNE is set
    temp = USART3->RDR;

    return temp;             // Read received data
}

int main(void)
{
	initGPIO();
	init_USART3();

	    while (1) {
	        USART3_SendChar('H');  // "H" harfini gönder
	        for (volatile int i = 0; i < 200000; i++) {} // Adjust the loop count for your desired delay

	        char c = USART3_ReceiveChar(); // Karakter al
	        if (c == 'A') {
	            USART3_SendChar('B'); // Eğer 'A' alındıysa 'B' gönder
	        }

	    }

}

