/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

// INTERRUPT için basic timer ile yazılmış bir kod
// led 1 sn aralıklar ile yanıp sönüyor.. wait() fonksiyonu yerine interrupt kullanılıyor
// pb5 pini output pini

// USER guide  300.sayfada NVIC -ISER memory adresleri yazıyor
// Reference manuelde chapter 16 da, sayfa 530 da --nvic

#include <stdbool.h>
#include <stdint.h>

typedef struct {
	volatile uint32_t CR1;
	volatile uint32_t CR2;
	volatile uint32_t SMCR;
	volatile uint32_t DIER;
	volatile uint32_t SR;
	volatile uint32_t EGR;
	volatile uint32_t CCMR1;
	volatile uint32_t CCMR2;
	volatile uint32_t CCER;
	volatile uint32_t CNT;
	volatile uint32_t PSC;
	volatile uint32_t ARR;
	uint32_t reserved1;
	volatile uint32_t CCR1;
	volatile uint32_t CCR2;
	volatile uint32_t CCR3;
	volatile uint32_t CCR4;
	uint32_t reserved2;
	volatile uint32_t DMAR;
} TIMX;

TIMX *TIM6 = (TIMX *) 0x40001000 ;

#define RCC_AHB2ENR *( (volatile uint32_t *) 0x4002104C)

#define RCC_APB1ENR1 *( (volatile uint32_t *) 0X40021058)

#define GPIOB_MODER *( (volatile uint32_t *) 0x42020400 )

#define GPIOB_ODR   *( (volatile uint32_t *)   0x42020414 )



#define NVIC_BASE_ADDR 0xE000E100
#define ISER1  *( (volatile uint32_t *)   0xE000E104 )





void init_leds (void){

	RCC_AHB2ENR |= (1<<1) ;   // port B clock open
	GPIOB_MODER &= ~(1 << 11); //PB5 is output

}

void turn_on_LED1(void){
	GPIOB_ODR |= (1<<5) ;
}

void turn_off_LED1() //assuming reset conditions
{
	GPIOB_ODR &= ~(1 << 5); //Write 1 to PB5

}

void init_TIM6 (){
	RCC_APB1ENR1 |=  1<<4;
	TIM6->PSC = 3999; //Set Prescaler
	TIM6->ARR = 999;  //Set Delay
	TIM6->CR1 &= ~(1<<1); //OVF will generate an event
	TIM6->CR1 |= (1<<7); //Enable autoreload of ARR register


	TIM6->DIER |= 1;

	ISER1 |= 1 << 17;//NEW! enable global signaling for TIM6 interrupt
	TIM6->CR1 |= 1; //TIM6_CNT is enabled (clocked)


}

void TIM6_IRQHandler (void){

	TIM6->SR=0; //clear UIF bit

}








int main(void)

{
	init_leds ();
	init_TIM6();

	__asm volatile(
		"mov r0, #0 \n\t"
		"msr primask, r0 \n\t "
	);


   while(1){

	   __asm volatile("wfi");  // wait for interrupt
	   turn_on_LED1(); //Turn on LED1
	   __asm volatile("wfi");
	   turn_off_LED1() ;  // turn off led1

   }
}

